// Generated by CoffeeScript 1.6.3
/*
(c) 2011 Jan Monschke
v1.0.1
GeoMock is licensed under the MIT license.
*/


(function() {
  (function() {
    if (typeof navigator === "undefined" || navigator === null) {
      window.navigator = {};
    }
    if (navigator.geolocation == null) {
      window.navigator.geolocation = {};
    }
    navigator.geolocation.delay = 1000;
    navigator.geolocation.shouldFail = false;
    navigator.geolocation.failsAt = -1;
    navigator.geolocation.errorMessage = "There was an error retrieving the position!";
    navigator.geolocation.currentTimeout = -1;
    navigator.geolocation.lastPosReturned = 0;
    navigator.geolocation._sanitizeLastReturned = function() {
      if (this.lastPosReturned > this.waypoints.length - 1) {
        return this.lastPosReturned = 0;
      }
    };
    navigator.geolocation._geoCall = function(method, success, error) {
      var _this = this;
      if (this.shouldFail && (error != null)) {
        return this.currentTimeout = window[method].call(null, function() {
          return error(_this.errorMessage);
        }, this.delay);
      } else {
        if (success != null) {
          return this.currentTimeout = window[method].call(null, function() {
            success(_this.waypoints[_this.lastPosReturned++]);
            return _this._sanitizeLastReturned();
          }, this.delay);
        }
      }
    };
    navigator.geolocation.getCurrentPosition = function(success, error) {
      return this._geoCall("setTimeout", success, error);
    };
    navigator.geolocation.watchPosition = function(success, error) {
      this._geoCall("setInterval", success, error);
      return this.currentTimeout;
    };
    navigator.geolocation.clearWatch = function(id) {
      return clearInterval(id);
    };
    return navigator.geolocation.waypoints = [
    /*  
    {
        coords: {
          latitude: 52.5168,
          longitude: 13.3889,
          accuracy: 1500
        }
      }, {
        coords: {
          latitude: 52.5162,
          longitude: 13.3890,
          accuracy: 1334
        }
      }, {
        coords: {
          latitude: 52.5154,
          longitude: 13.3890,
          accuracy: 631
        }
      }, {
        coords: {
          latitude: 52.5150,
          longitude: 13.3890,
          accuracy: 361
        }
      }, {
        coords: {
          latitude: 52.5144,
          longitude: 13.3890,
          accuracy: 150
        }
      }, {
        coords: {
          latitude: 52.5138,
          longitude: 13.3890,
          accuracy: 65
        }
      }, {
        coords: {
          latitude: 52.5138,
          longitude: 13.3895,
          accuracy: 65
        }
      }, {
        coords: {
          latitude: 52.5139,
          longitude: 13.3899,
          accuracy: 65
        }
      }, {
        coords: {
          latitude: 52.5140,
          longitude: 13.3906,
          accuracy: 65
        }
      }, {
        coords: {
          latitude: 52.5140,
          longitude: 13.3910,
          accuracy: 65
        }
      }*/
{coords: {

  latitude: 47.0916
  longitute: 15.8813
  accuracy: 0
}},
{coords: {

  latitude: 47.0912
  longitute: 15.8829
  accuracy: 0
}},
{coords: {

  latitude: 47.0908
  longitute: 15.8852
  accuracy: 0
}},
{coords: {

  latitude: 47.0903
  longitute: 15.8872
  accuracy: 0
}},
{coords: {

  latitude: 47.0899
  longitute: 15.8895
  accuracy: 0
}},
{coords: {

  latitude: 47.0898
  longitute: 15.8902
  accuracy: 0
}},
{coords: {

  latitude: 47.0895
  longitute: 15.8917
  accuracy: 0
}},
{coords: {

  latitude: 47.0891
  longitute: 15.8948
  accuracy: 0
}},
{coords: {

  latitude: 47.0891
  longitute: 15.8954
  accuracy: 0
}},
{coords: {

  latitude: 47.0891
  longitute: 15.8954
  accuracy: 0
}},
{coords: {

  latitude: 47.0892
  longitute: 15.8983
  accuracy: 0
}},
{coords: {

  latitude: 47.0894
  longitute: 15.901
  accuracy: 0
}},
{coords: {

  latitude: 47.0903
  longitute: 15.9039
  accuracy: 0
}},
{coords: {

  latitude: 47.0909
  longitute: 15.9068
  accuracy: 0
}},
{coords: {

  latitude: 47.0906
  longitute: 15.9091
  accuracy: 0
}},
{coords: {

  latitude: 47.0905
  longitute: 15.9094
  accuracy: 0
}},
{coords: {

  latitude: 47.0905
  longitute: 15.9094
  accuracy: 0
}},
{coords: {

  latitude: 47.0899
  longitute: 15.9112
  accuracy: 0
}},
{coords: {

  latitude: 47.089
  longitute: 15.9136
  accuracy: 0
}},
{coords: {

  latitude: 47.0879
  longitute: 15.9157
  accuracy: 0
}},
{coords: {

  latitude: 47.0872
  longitute: 15.9178
  accuracy: 0
}},
{coords: {

  latitude: 47.0871
  longitute: 15.922
  accuracy: 0
}},
{coords: {

  latitude: 47.087
  longitute: 15.9219
  accuracy: 0
}},
{coords: {

  latitude: 47.0869
  longitute: 15.9236
  accuracy: 0
}},
{coords: {

  latitude: 47.0865
  longitute: 15.9251
  accuracy: 0
}},
{coords: {

  latitude: 47.0865
  longitute: 15.9263
  accuracy: 0
}},
{coords: {

  latitude: 47.0864
  longitute: 15.9266
  accuracy: 0
}},
{coords: {

  latitude: 47.0864
  longitute: 15.9266
  accuracy: 0
}},
{coords: {

  latitude: 47.0864
  longitute: 15.9273
  accuracy: 0
}},
{coords: {

  latitude: 47.0863
  longitute: 15.9273
  accuracy: 0
}},
{coords: {

  latitude: 47.0863
  longitute: 15.9282
  accuracy: 0
}},
{coords: {

  latitude: 47.0864
  longitute: 15.9305
  accuracy: 0
}},
{coords: {

  latitude: 47.0863
  longitute: 15.933
  accuracy: 0
}},
{coords: {

  latitude: 47.0856
  longitute: 15.9354
  accuracy: 0
}},
{coords: {

  latitude: 47.0848
  longitute: 15.9379
  accuracy: 0
}},
{coords: {

  latitude: 47.084
  longitute: 15.9405
  accuracy: 0
}},
{coords: {

  latitude: 47.0834
  longitute: 15.9426
  accuracy: 0
}},
{coords: {

  latitude: 47.0834
  longitute: 15.9426
  accuracy: 0
}},
{coords: {

  latitude: 47.0831
  longitute: 15.9433
  accuracy: 0
}},
{coords: {

  latitude: 47.083
  longitute: 15.9433
  accuracy: 0
}},
{coords: {

  latitude: 47.083
  longitute: 15.9446
  accuracy: 0
}},
{coords: {

  latitude: 47.0833
  longitute: 15.9467
  accuracy: 0
}},
{coords: {

  latitude: 47.0834
  longitute: 15.9497
  accuracy: 0
}},
{coords: {

  latitude: 47.083
  longitute: 15.9527
  accuracy: 0
}},
{coords: {

  latitude: 47.0827
  longitute: 15.9551
  accuracy: 0
}},
{coords: {

  latitude: 47.0819
  longitute: 15.9578
  accuracy: 0
}},
{coords: {

  latitude: 47.0808
  longitute: 15.9603
  accuracy: 0
}},
{coords: {

  latitude: 47.0797
  longitute: 15.9623
  accuracy: 0
}},
{coords: {

  latitude: 47.0787
  longitute: 15.9642
  accuracy: 0
}},
{coords: {

  latitude: 47.0776
  longitute: 15.9662
  accuracy: 0
}},
{coords: {

  latitude: 47.0764
  longitute: 15.9686
  accuracy: 0
}},
{coords: {

  latitude: 47.0754
  longitute: 15.9714
  accuracy: 0
}},
{coords: {

  latitude: 47.0746
  longitute: 15.9738
  accuracy: 0
}},
{coords: {

  latitude: 47.0746
  longitute: 15.9738
  accuracy: 0
}},
{coords: {

  latitude: 47.0737
  longitute: 15.9768
  accuracy: 0
}},
{coords: {

  latitude: 47.0733
  longitute: 15.9795
  accuracy: 0
}},
{coords: {

  latitude: 47.0734
  longitute: 15.9826
  accuracy: 0
}},
{coords: {

  latitude: 47.074
  longitute: 15.9853
  accuracy: 0
}},
{coords: {

  latitude: 47.0747
  longitute: 15.9873
  accuracy: 0
}},
{coords: {

  latitude: 47.0755
  longitute: 15.9893
  accuracy: 0
}},
{coords: {

  latitude: 47.0764
  longitute: 15.9907
  accuracy: 0
}},
{coords: {

  latitude: 47.0773
  longitute: 15.9921
  accuracy: 0
}},
{coords: {

  latitude: 47.0778
  longitute: 15.9935
  accuracy: 0
}},
{coords: {

  latitude: 47.0776
  longitute: 15.9941
  accuracy: 0
}},
{coords: {

  latitude: 47.0776
  longitute: 15.9941
  accuracy: 0
}},
{coords: {

  latitude: 47.0774
  longitute: 15.9946
  accuracy: 0
}},
{coords: {

  latitude: 47.0773
  longitute: 15.9947
  accuracy: 0
}},
{coords: {

  latitude: 47.0773
  longitute: 15.9948
  accuracy: 0
}},
{coords: {

  latitude: 47.0773
  longitute: 15.9948
  accuracy: 0
}},
{coords: {

  latitude: 47.0773
  longitute: 15.9949
  accuracy: 0
}},
{coords: {

  latitude: 47.0773
  longitute: 15.9949
  accuracy: 0
}}
    ];
  })();

}).call(this);
